---
name: sheetrem
description: App to store when you changed the sheets
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  lint: ^1.5.3
  freezed: ^0.14.1+1
flutter:
  uses-material-design: true
  assets:
    - lang/en.json
    - lang/es.json
